project:
  type: website
  resources:
    - google9a858fb572e6e87d.html
    - M08/
  render: 
    - "*.qmd"
    - "!M08/*.qmd"


website:
  title: "Alejandro Camara"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: dashboard.qmd
        text: Dashboard
      - href: revealjs-presentation.qmd
        text: Revealjs Presentation
      - href: google-analytics.qmd
        text: Google Analytics

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: "Helvetica, Arial, sans-serif"
    fontsize: 16px



